takeoff:
  server_config:
    batch_duration_millis: 10
  readers_config:
    model_2:
      model_name: Salesforce/SFR-Embedding-Mistral
      device: cuda
      consumer_group: embed
      log_level: warning
